/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcaremax.view;

import com.petcaremax.controller.CustomerFormController;

import com.petcaremax.controller.CustomerController;
import com.petcaremax.model.Customer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import com.petcaremax.util.PetCareTheme;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Customer Management Form
 *
 * Responsibilities:
 * - Create, read, update and delete customers
 * - Search customers using ArrayList + Stream + Lambda
 * - Display customer records in a professional Swing UI
 *
 * The controller/service/DAO/database logic is kept separate.
 */
public class CustomerForm extends JFrame {
    private final CustomerFormController formController;


    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CustomerForm.class.getName());

    // CONTROLLER

    private final CustomerController customerController;

    // CONSTRUCTOR

    public CustomerForm() {

        /*
         * Creates the Swing components.
         * In the original NetBeans project this section is generated
         * by the GUI Builder.
         */
        initComponents();

    formController = new CustomerFormController(this);

        // Create controller.
        customerController = new CustomerController();

        // BUTTON EVENTS
        // TABLE ROW SELECTION

        jTable1.addMouseListener(
                new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseClicked(
                            java.awt.event.MouseEvent evt
                    ) {
                        loadSelectedCustomer();
                    }
                }
        );

        // Load database records.
        loadCustomers();
        PetCareTheme.apply(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetCareMAX - Customer Management");
        setPreferredSize(new java.awt.Dimension(1280, 760));

        // NetBeans form uses AbsoluteLayout for the JFrame content pane.
        // This must be set before adding jPanel1 with AbsoluteConstraints.
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // PAGE HEADER
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30));
        jLabel1.setForeground(new java.awt.Color(35, 40, 50));
        jLabel1.setText("Customer Management");
        jPanel1.add(jLabel1,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, 500, 40));

        // SECTION TITLES
        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        jLabel2.setForeground(new java.awt.Color(35, 40, 50));
        jLabel2.setText("Customer Information");
        jPanel1.add(jLabel2,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 125, 350, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        jLabel3.setForeground(new java.awt.Color(35, 40, 50));
        jLabel3.setText("Customer List");
        jPanel1.add(jLabel3,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 125, 300, 30));

        // FIELD LABELS
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        jLabel4.setForeground(new java.awt.Color(35, 40, 50));
        jLabel4.setText("Full Name");
        jPanel1.add(jLabel4,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 180, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        jLabel5.setForeground(new java.awt.Color(35, 40, 50));
        jLabel5.setText("Phone");
        jPanel1.add(jLabel5,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 250, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        jLabel6.setForeground(new java.awt.Color(35, 40, 50));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 320, 120, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        jLabel7.setForeground(new java.awt.Color(35, 40, 50));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 390, 120, 20));

        // INPUT FIELDS
        txtFullName.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtFullName.setForeground(new java.awt.Color(35, 40, 50));
        jPanel1.add(txtFullName,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 202, 382, 40));

        txtPhone.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtPhone.setForeground(new java.awt.Color(35, 40, 50));
        jPanel1.add(txtPhone,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 272, 382, 40));

        txtEmail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtEmail.setForeground(new java.awt.Color(35, 40, 50));
        jPanel1.add(txtEmail,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 342, 382, 40));

        txtAddress.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtAddress.setForeground(new java.awt.Color(35, 40, 50));
        jPanel1.add(txtAddress,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 412, 382, 40));

        // ACTION BUTTONS
        btnSave.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnSave.setForeground(new java.awt.Color(35, 40, 50));
        btnSave.setText("Save");
        jPanel1.add(btnSave,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 480, 86, 36));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnUpdate.setForeground(new java.awt.Color(35, 40, 50));
        btnUpdate.setText("Update");
        jPanel1.add(btnUpdate,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 86, 36));

        btnDelete.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnDelete.setText("Delete");
        jPanel1.add(btnDelete,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 480, 86, 36));

        btnClear.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnClear.setForeground(new java.awt.Color(35, 40, 50));
        btnClear.setText("Clear");
        jPanel1.add(btnClear,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 480, 94, 36));

        // SEARCH
        jLabel8.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        jLabel8.setText("Search Customer");
        jPanel1.add(jLabel8,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 140, 20));

        txtSearch.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        txtSearch.setForeground(new java.awt.Color(35, 40, 50));
        jPanel1.add(txtSearch,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 174, 420, 40));

        btnSearch.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnSearch.setForeground(new java.awt.Color(35, 40, 50));
        btnSearch.setText("Search");
        jPanel1.add(btnSearch,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 177, 86, 34));

        // CUSTOMER TABLE
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Full Name", "Phone", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jTable1.setForeground(new java.awt.Color(35, 40, 50));
        jTable1.setRowHeight(36);
        jTable1.setSelectionForeground(new java.awt.Color(35, 40, 50));
        jTable1.setShowHorizontalLines(true);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 656, 450));

        getContentPane().add(jPanel1,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 760));

        pack();
        setSize(1280, 760);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // SAVE CUSTOMER

    public void saveCustomer() {

        try {

            String name =
                    txtFullName.getText().trim();

            String phone =
                    txtPhone.getText().trim();

            String email =
                    txtEmail.getText().trim();

            String address =
                    txtAddress.getText().trim();

            boolean saved =
                    customerController.addCustomer(
                            name,
                            phone,
                            email,
                            address
                    );

            if (saved) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer saved successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be saved.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // UPDATE CUSTOMER

    public void updateCustomer() {

        int row =
                jTable1.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer from the table first.",
                    "No Customer Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            // Convert the displayed row back to the model row
            // because table sorting is enabled.
            int modelRow =
                    jTable1.convertRowIndexToModel(row);

            int id =
                    Integer.parseInt(
                            jTable1
                                    .getModel()
                                    .getValueAt(
                                            modelRow,
                                            0
                                    )
                                    .toString()
                    );

            String name =
                    txtFullName.getText().trim();

            String phone =
                    txtPhone.getText().trim();

            String email =
                    txtEmail.getText().trim();

            String address =
                    txtAddress.getText().trim();

            boolean updated =
                    customerController.updateCustomer(
                            id,
                            name,
                            phone,
                            email,
                            address
                    );

            if (updated) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer updated successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be updated.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error updating customer:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // CLEAR

    public void clearCustomer() {

        clearFields();

        jTable1.clearSelection();

        txtSearch.setText("");

        loadCustomers();
    }

    // SEARCH

    public void searchCustomers() {

        String searchText =
                txtSearch.getText()
                        .trim()
                        .toLowerCase();

        if (searchText.isEmpty()) {

            loadCustomers();

            return;
        }

        try {

            /*
             * ArrayList is intentionally used here
             * for the coursework Collections requirement.
             */
            ArrayList<Customer> customers =
                    new ArrayList<>(
                            customerController
                                    .getAllCustomers()
                    );

            /*
             * Lambda + Stream filtering.
             */
            List<Customer> filtered =
                    customers.stream()
                            .filter(
                                    customer ->
                                            String.valueOf(
                                                    customer.getCustomerId()
                                            ).contains(searchText)

                                            ||

                                            customer.getFullName()
                                                    .toLowerCase()
                                                    .contains(searchText)

                                            ||

                                            customer.getPhone()
                                                    .toLowerCase()
                                                    .contains(searchText)

                                            ||

                                            (
                                                    customer.getEmail() != null
                                                    &&
                                                    customer.getEmail()
                                                            .toLowerCase()
                                                            .contains(searchText)
                                            )
                            )
                            .collect(
                                    Collectors.toList()
                            );

            displayCustomers(
                    filtered
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error searching customers:\n"
                    + e.getMessage(),
                    "Search Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // LOAD CUSTOMERS

    private void loadCustomers() {

        try {

            List<Customer> customers =
                    customerController
                            .getAllCustomers();

            displayCustomers(
                    customers
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load customers:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // DISPLAY CUSTOMERS

    private void displayCustomers(
            List<Customer> customers
    ) {

        DefaultTableModel model =
                (DefaultTableModel)
                        jTable1.getModel();

        model.setRowCount(0);

        for (Customer customer : customers) {

            model.addRow(
                    new Object[]{
                            customer.getCustomerId(),
                            customer.getFullName(),
                            customer.getPhone(),
                            customer.getEmail() == null
                                    ? ""
                                    : customer.getEmail(),
                            customer.getAddress() == null
                                    ? ""
                                    : customer.getAddress()
                    }
            );
        }
    }

    // LOAD SELECTED CUSTOMER

    private void loadSelectedCustomer() {

        int row =
                jTable1.getSelectedRow();

        if (row == -1) {
            return;
        }

        int modelRow =
                jTable1.convertRowIndexToModel(row);

        txtFullName.setText(
                valueFromTable(
                        modelRow,
                        1
                )
        );

        txtPhone.setText(
                valueFromTable(
                        modelRow,
                        2
                )
        );

        txtEmail.setText(
                valueFromTable(
                        modelRow,
                        3
                )
        );

        txtAddress.setText(
                valueFromTable(
                        modelRow,
                        4
                )
        );
    }

    // TABLE VALUE HELPER

    private String valueFromTable(
            int row,
            int column
    ) {

        Object value =
                jTable1.getModel().getValueAt(
                        row,
                        column
                );

        return value == null
                ? ""
                : value.toString();
    }

    // CLEAR FIELDS

    private void clearFields() {

        txtFullName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");

        txtFullName.requestFocus();
    }

     // DELETE CUSTOMER
    
    public void deleteCustomer() {
        // Button actions are handled by the form controller.
     

        int row =
                jTable1.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer to delete.",
                    "No Customer Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            int id =
                    Integer.parseInt(
                            jTable1
                                    .getValueAt(row, 0)
                                    .toString()
                    );

            String name =
                    jTable1
                            .getValueAt(row, 1)
                            .toString();

            int confirmation =
                    JOptionPane.showConfirmDialog(
                            this,
                            "Delete customer:\n"
                            + name
                            + "?",
                            "Confirm Delete",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );

            if (confirmation !=
                    JOptionPane.YES_OPTION) {

                return;
            }

            boolean deleted =
                    customerController.deleteCustomer(
                            id
                    );

            if (deleted) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer deleted successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be deleted.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error deleting customer:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    :
                    javax.swing.UIManager
                            .getInstalledLookAndFeels()
            ) {

                if (
                        "Nimbus".equals(
                                info.getName()
                        )
                ) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                |
                javax.swing.UnsupportedLookAndFeelException ex
        ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

         java.awt.EventQueue.invokeLater(
            () -> {

                CustomerForm form =
                        new CustomerForm();

                form.setVisible(true);
            }
    );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Button accessors are used by the controller.
    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }
    public javax.swing.JButton getBtnUpdate() {
        return btnUpdate;
    }
    public javax.swing.JButton getBtnDelete() {
        return btnDelete;
    }
    public javax.swing.JButton getBtnClear() {
        return btnClear;
    }
    public javax.swing.JButton getBtnSearch() {
        return btnSearch;
    }

}
