/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcaremax.view;
import com.petcaremax.controller.CustomerController;
import com.petcaremax.model.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
/**
 *
 * @author Bimsara
 */
public class CustomerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CustomerForm.class.getName());

    //controller
    
    private final CustomerController customerController;
    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
         customerController =
                new CustomerController();

        // Connect button events
        btnSave.addActionListener(
                this::btnSaveActionPerformed
        );

        btnUpdate.addActionListener(
                this::btnUpdateActionPerformed
        );

        btnDelete.addActionListener(
                this::btnDeleteActionPerformed
        );

        btnClear.addActionListener(
                this::btnClearActionPerformed
        );

        btnSearch.addActionListener(
                this::btnSearchActionPerformed
        );

        // When user clicks a table row
        tblCustomers.addMouseListener(
                new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseClicked(
                            java.awt.event.MouseEvent evt
                    ) {

                        loadSelectedCustomer();
                    }
                }
        );

        // Load database records
        loadCustomers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        jLabel2.setText("Customer Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 30));

        jLabel3.setText("Customer List");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, -1));

        jLabel4.setText("Full Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, -1));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, -1));

        btnSave.setText("Save");
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnUpdate.setText("Update");
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnClear.setText("Clear");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel8.setText("Search Customer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, -1));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, -1));

        btnSearch.setText("Search");
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Phone", "Email", "Address"
            }
        ));
        tblCustomers.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tblCustomers);
        tblCustomers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 330, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ============================================================
    // SAVE CUSTOMER
    // ============================================================

    private void btnSaveActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        try {

            String name =
                    txtFullName.getText().trim();

            String phone =
                    txtPhone.getText().trim();

            String email =
                    txtEmail.getText().trim();

            String address =
                    txtAddress.getText().trim();

            boolean saved =
                    customerController.addCustomer(
                            name,
                            phone,
                            email,
                            address
                    );

            if (saved) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer saved successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be saved.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException  e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // ============================================================
    // UPDATE CUSTOMER
    // ============================================================

    private void btnUpdateActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        int row =
                tblCustomers.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer from the table first.",
                    "No Customer Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            int id =
                    Integer.parseInt(
                            tblCustomers
                                    .getValueAt(row, 0)
                                    .toString()
                    );

            String name =
                    txtFullName.getText().trim();

            String phone =
                    txtPhone.getText().trim();

            String email =
                    txtEmail.getText().trim();

            String address =
                    txtAddress.getText().trim();

            boolean updated =
                    customerController.updateCustomer(
                            id,
                            name,
                            phone,
                            email,
                            address
                    );

            if (updated) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer updated successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be updated.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error updating customer:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // CLEAR
    // ============================================================

    private void btnClearActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        clearFields();

        tblCustomers.clearSelection();

        txtSearch.setText("");

        loadCustomers();
    }

    // ============================================================
    // SEARCH
    // ============================================================

    private void btnSearchActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        String searchText =
                txtSearch.getText()
                        .trim()
                        .toLowerCase();

        if (searchText.isEmpty()) {

            loadCustomers();

            return;
        }

        try {

            /*
             * ArrayList is intentionally used here
             * for the coursework Collections requirement.
             */

            ArrayList<Customer> customers =
                    new ArrayList<>(
                            customerController
                                    .getAllCustomers()
                    );

            /*
             * Lambda + Stream filtering.
             */

            List<Customer> filtered =
                    customers.stream()
                            .filter(customer ->
                                    String.valueOf(
                                            customer.getCustomerId()
                                    ).contains(searchText)

                                    ||

                                    customer.getFullName()
                                            .toLowerCase()
                                            .contains(searchText)

                                    ||

                                    customer.getPhone()
                                            .toLowerCase()
                                            .contains(searchText)

                                    ||

                                    (
                                        customer.getEmail() != null
                                        &&
                                        customer.getEmail()
                                                .toLowerCase()
                                                .contains(searchText)
                                    )
                            )
                            .collect(
                                    Collectors.toList()
                            );

            displayCustomers(filtered);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error searching customers:\n"
                    + e.getMessage(),
                    "Search Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // ============================================================
    // LOAD CUSTOMERS
    // ============================================================

    private void loadCustomers() {

        try {

            List<Customer> customers =
                    customerController
                            .getAllCustomers();

            displayCustomers(customers);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load customers:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }

    // ============================================================
    // DISPLAY CUSTOMERS IN TABLE
    // ============================================================

    private void displayCustomers(
            List<Customer> customers
    ) {

        DefaultTableModel model =
                (DefaultTableModel)
                        tblCustomers.getModel();

        model.setRowCount(0);

        for (Customer customer : customers) {

            model.addRow(
                    new Object[]{
                        customer.getCustomerId(),
                        customer.getFullName(),
                        customer.getPhone(),
                        customer.getEmail() == null
                                ? ""
                                : customer.getEmail(),
                        customer.getAddress() == null
                                ? ""
                                : customer.getAddress()
                    }
            );
        }
    }

    // ============================================================
    // LOAD SELECTED CUSTOMER
    // ============================================================

    private void loadSelectedCustomer() {

        int row =
                tblCustomers.getSelectedRow();

        if (row == -1) {
            return;
        }

        txtFullName.setText(
                valueFromTable(row, 1)
        );

        txtPhone.setText(
                valueFromTable(row, 2)
        );

        txtEmail.setText(
                valueFromTable(row, 3)
        );

        txtAddress.setText(
                valueFromTable(row, 4)
        );
    }

    // ============================================================
    // TABLE VALUE HELPER
    // ============================================================

    private String valueFromTable(
            int row,
            int column
    ) {

        Object value =
                tblCustomers.getValueAt(
                        row,
                        column
                );

        return value == null
                ? ""
                : value.toString();
    }

    // ============================================================
    // CLEAR FIELDS
    // ============================================================

    private void clearFields() {

        txtFullName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");

        txtFullName.requestFocus();
    }
     // DELETE CUSTOMER
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here: private void btnDeleteActionPerformed(

     {

        int row =
                tblCustomers.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer to delete.",
                    "No Customer Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            int id =
                    Integer.parseInt(
                            tblCustomers
                                    .getValueAt(row, 0)
                                    .toString()
                    );

            String name =
                    tblCustomers
                            .getValueAt(row, 1)
                            .toString();

            int confirmation =
                    JOptionPane.showConfirmDialog(
                            this,
                            "Delete customer:\n"
                            + name
                            + "?",
                            "Confirm Delete",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );

            if (confirmation !=
                    JOptionPane.YES_OPTION) {

                return;
            }

            boolean deleted =
                    customerController.deleteCustomer(
                            id
                    );

            if (deleted) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer deleted successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadCustomers();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be deleted.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error deleting customer:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    :
                    javax.swing.UIManager
                            .getInstalledLookAndFeels()
            ) {

                if (
                        "Nimbus".equals(
                                info.getName()
                        )
                ) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                |
                javax.swing.UnsupportedLookAndFeelException ex
        ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        java.awt.EventQueue.invokeLater(
                () ->
                        new CustomerForm()
                                .setVisible(true)
        );
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
