/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcaremax.view;
import com.petcaremax.controller.CustomerController;
import com.petcaremax.controller.PetController;
import com.petcaremax.model.Customer;
import com.petcaremax.model.Pet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
/**
 *
 * @author Bimsara
 */
public class PetForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(PetForm.class.getName());

    // Controllers
    private final PetController petController;
    private final CustomerController customerController;

    // Collections
    private List<Pet> currentPets = new ArrayList<>();
    private List<Customer> customers = new ArrayList<>();

    /**
     * Creates new form PetMangementForm
     */
    public PetForm() {
        initComponents();
         // Create controllers
        petController = new PetController();
        customerController = new CustomerController();

        // Connect buttons that are not already connected
        btnDelete.addActionListener(
                this::btnDeleteActionPerformed
        );

        btnClear.addActionListener(
                this::btnClearActionPerformed
        );

       

        // Table row selection
        tblPets.addMouseListener(
                new java.awt.event.MouseAdapter() {

                    @Override
                    public void mouseClicked(
                            java.awt.event.MouseEvent evt
                    ) {
                        loadSelectedPet();
                    }
                }
        );

        // Load data
        loadCustomers();
        loadPets();

        // Center window
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbSpecies = new javax.swing.JComboBox<>();
        txtBreed = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtDateOfBirth = new javax.swing.JTextField();
        cmbOwner = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPets = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pet Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, -1));

        jLabel2.setText("Species");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setText("Breed");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("Date of Birth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, -1));

        jLabel6.setText("Owner ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(txtPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        jLabel7.setText("Pet Management ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel8.setText("Pet Information");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        cmbSpecies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Bird", "Rabbit", "Other" }));
        jPanel1.add(cmbSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));
        jPanel1.add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));
        jPanel1.add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, -1));

        cmbOwner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        btnDelete.setText("Delete");
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        btnClear.setText("Clear");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel9.setText("Search Pet");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, -1));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 150, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLabel10.setText("Pet List");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        tblPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Species", "Breed", "Gender", "DOB", "Weight", "Owner", "Notes"
            }
        ));
        jScrollPane1.setViewportView(tblPets);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 420, 120));

        jLabel11.setText("Weight");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, -1));

        jLabel12.setText("Notes");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 280, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         int row = tblPets.getSelectedRow();
try {

            String petName =
                    txtPetName.getText().trim();

            String species =
                    cmbSpecies.getSelectedItem() == null
                            ? ""
                            : cmbSpecies.getSelectedItem().toString();

            String breed =
                    txtBreed.getText().trim();

            String gender =
                    cmbGender.getSelectedItem() == null
                            ? ""
                            : cmbGender.getSelectedItem().toString();

            String dobText =
                    txtDateOfBirth.getText().trim();

            String weightText =
                    txtWeight.getText().trim();

            String notes =
                    txtNotes.getText().trim();


            // ----------------------------------------------------
            // Get selected owner
            // ----------------------------------------------------

            int ownerIndex =
                    cmbOwner.getSelectedIndex();

            if (ownerIndex < 0
                    || ownerIndex >= customers.size()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select an owner.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }

            Customer selectedCustomer =
                    customers.get(ownerIndex);

            int customerId =
                    selectedCustomer.getCustomerId();


            // ----------------------------------------------------
            // Date of birth
            // ----------------------------------------------------

            LocalDate dateOfBirth = null;

            if (!dobText.isEmpty()) {

                try {

                    dateOfBirth =
                            LocalDate.parse(dobText);

                } catch (DateTimeParseException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Invalid date format.\n"
                            + "Please use YYYY-MM-DD.",
                            "Validation Error",
                            JOptionPane.WARNING_MESSAGE
                    );

                    return;
                }
            }


            // ----------------------------------------------------
            // Weight
            // ----------------------------------------------------

            Double weight = null;

            if (!weightText.isEmpty()) {

                try {

                    weight =
                            Double.parseDouble(weightText);

                } catch (NumberFormatException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Weight must be a valid number.",
                            "Validation Error",
                            JOptionPane.WARNING_MESSAGE
                    );

                    return;
                }
            }


            // ----------------------------------------------------
            // Create Pet object
            // ----------------------------------------------------

            Pet pet = new Pet(
                    0,
                    customerId,
                    petName,
                    species,
                    breed,
                    gender,
                    dateOfBirth,
                    weight,
                    notes
            );


            // ----------------------------------------------------
            // Save
            // ----------------------------------------------------

            boolean saved =
                    petController.addPet(pet);

            if (saved) {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet saved successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadPets();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet could not be saved.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row =
                tblPets.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a pet from the table first.",
                    "No Pet Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        if (row >= currentPets.size()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid pet selection.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        try {

            Pet selectedPet =
                    currentPets.get(row);

            int petId =
                    selectedPet.getPetId();


            String petName =
                    txtPetName.getText().trim();

            String species =
                    cmbSpecies.getSelectedItem() == null
                            ? ""
                            : cmbSpecies.getSelectedItem().toString();

            String breed =
                    txtBreed.getText().trim();

            String gender =
                    cmbGender.getSelectedItem() == null
                            ? ""
                            : cmbGender.getSelectedItem().toString();

            String dobText =
                    txtDateOfBirth.getText().trim();

            String weightText =
                    txtWeight.getText().trim();

            String notes =
                    txtNotes.getText().trim();


            // ----------------------------------------------------
            // Owner
            // ----------------------------------------------------

            int ownerIndex =
                    cmbOwner.getSelectedIndex();

            if (ownerIndex < 0
                    || ownerIndex >= customers.size()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select an owner.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }

            Customer selectedCustomer =
                    customers.get(ownerIndex);

            int customerId =
                    selectedCustomer.getCustomerId();


            // ----------------------------------------------------
            // Date
            // ----------------------------------------------------

            LocalDate dateOfBirth = null;

            if (!dobText.isEmpty()) {

                try {

                    dateOfBirth =
                            LocalDate.parse(dobText);

                } catch (DateTimeParseException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Invalid date format.\n"
                            + "Please use YYYY-MM-DD.",
                            "Validation Error",
                            JOptionPane.WARNING_MESSAGE
                    );

                    return;
                }
            }


            // ----------------------------------------------------
            // Weight
            // ----------------------------------------------------

            Double weight = null;

            if (!weightText.isEmpty()) {

                try {

                    weight =
                            Double.parseDouble(weightText);

                } catch (NumberFormatException e) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Weight must be a valid number.",
                            "Validation Error",
                            JOptionPane.WARNING_MESSAGE
                    );

                    return;
                }
            }


            // ----------------------------------------------------
            // Create updated Pet
            // ----------------------------------------------------

            Pet pet = new Pet(
                    petId,
                    customerId,
                    petName,
                    species,
                    breed,
                    gender,
                    dateOfBirth,
                    weight,
                    notes
            );


            // ----------------------------------------------------
            // Update
            // ----------------------------------------------------

            boolean updated =
                    petController.updatePet(pet);

            if (updated) {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet updated successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadPets();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet could not be updated.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // DELETE PET
    // ============================================================

    private void btnDeleteActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        int row =
                tblPets.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a pet from the table first.",
                    "No Pet Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        if (row >= currentPets.size()) {
            return;
        }

        try {

            Pet selectedPet =
                    currentPets.get(row);

            int petId =
                    selectedPet.getPetId();

            int confirmation =
                    JOptionPane.showConfirmDialog(
                            this,
                            "Are you sure you want to delete this pet?",
                            "Confirm Delete",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );

            if (confirmation != JOptionPane.YES_OPTION) {
                return;
            }

            boolean deleted =
                    petController.deletePet(petId);

            if (deleted) {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet deleted successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();

                loadPets();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Pet could not be deleted.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error deleting pet:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // CLEAR
    // ============================================================

    private void btnClearActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        clearFields();

        tblPets.clearSelection();

        txtSearch.setText("");

        loadPets();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchText =
                txtSearch.getText()
                        .trim()
                        .toLowerCase();

        if (searchText.isEmpty()) {

            loadPets();

            return;
        }

        try {

            ArrayList<Pet> pets =
                    new ArrayList<>(
                            petController.getAllPets()
                    );

            List<Pet> filtered =
                    pets.stream()

                            .filter(pet ->

                                    String.valueOf(
                                            pet.getPetId()
                                    )
                                    .contains(searchText)

                                    ||

                                    pet.getPetName()
                                            .toLowerCase()
                                            .contains(searchText)

                                    ||

                                    pet.getSpecies()
                                            .toLowerCase()
                                            .contains(searchText)

                                    ||

                                    (
                                        pet.getBreed() != null
                                        &&
                                        pet.getBreed()
                                                .toLowerCase()
                                                .contains(searchText)
                                    )

                                    ||

                                    getOwnerName(
                                            pet.getCustomerId()
                                    )
                                    .toLowerCase()
                                    .contains(searchText)

                            )

                            .collect(
                                    Collectors.toList()
                            );

            currentPets =
                    new ArrayList<>(filtered);

            displayPets(filtered);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error searching pets:\n"
                    + e.getMessage(),
                    "Search Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // LOAD CUSTOMERS
    // ============================================================

    private void loadCustomers() {

        try {

            customers =
                    new ArrayList<>(
                            customerController.getAllCustomers()
                    );

            cmbOwner.removeAllItems();

            for (Customer customer : customers) {

                cmbOwner.addItem(
                        customer.getFullName()
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load owners:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // LOAD PETS
    // ============================================================

    private void loadPets() {

        try {

            currentPets =
                    new ArrayList<>(
                            petController.getAllPets()
                    );

            displayPets(currentPets);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load pets:\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }


    // ============================================================
    // DISPLAY PETS IN TABLE
    // ============================================================

    private void displayPets(
            List<Pet> pets
    ) {

        DefaultTableModel model =
                (DefaultTableModel) tblPets.getModel();

        model.setRowCount(0);

        for (Pet pet : pets) {

            model.addRow(
                    new Object[]{

                        pet.getPetId(),

                        pet.getPetName(),

                        pet.getSpecies(),

                        pet.getBreed() == null
                                ? ""
                                : pet.getBreed(),

                        pet.getGender(),

                        pet.getDateOfBirth() == null
                                ? ""
                                : pet.getDateOfBirth(),

                        pet.getWeight() == null
                                ? ""
                                : pet.getWeight(),

                        getOwnerName(
                                pet.getCustomerId()
                        ),

                        pet.getNotes() == null
                                ? ""
                                : pet.getNotes()
                    }
            );
        }
    }


    // ============================================================
    // GET OWNER NAME
    // ============================================================

    private String getOwnerName(
            int customerId
    ) {

        return customers.stream()

                .filter(customer ->
                        customer.getCustomerId()
                        == customerId
                )

                .map(Customer::getFullName)

                .findFirst()

                .orElse("Unknown");
    }


    // ============================================================
    // LOAD SELECTED PET
    // ============================================================

    private void loadSelectedPet() {

        int row =
                tblPets.getSelectedRow();

        if (row == -1) {
            return;
        }

        if (row >= currentPets.size()) {
            return;
        }

        Pet pet =
                currentPets.get(row);


        txtPetName.setText(
                pet.getPetName()
        );


        cmbSpecies.setSelectedItem(
                pet.getSpecies()
        );


        txtBreed.setText(
                pet.getBreed() == null
                        ? ""
                        : pet.getBreed()
        );


        cmbGender.setSelectedItem(
                pet.getGender()
        );


        txtDateOfBirth.setText(
                pet.getDateOfBirth() == null
                        ? ""
                        : pet.getDateOfBirth().toString()
        );


        txtWeight.setText(
                pet.getWeight() == null
                        ? ""
                        : pet.getWeight().toString()
        );


        txtNotes.setText(
                pet.getNotes() == null
                        ? ""
                        : pet.getNotes()
        );


        selectOwner(
                pet.getCustomerId()
        );
    }


    // ============================================================
    // SELECT OWNER
    // ============================================================

    private void selectOwner(
            int customerId
    ) {

        for (int i = 0;
                i < customers.size();
                i++) {

            Customer customer =
                    customers.get(i);

            if (customer.getCustomerId()
                    == customerId) {

                cmbOwner.setSelectedIndex(i);

                return;
            }
        }
    }


    // ============================================================
    // CLEAR FIELDS
    // ============================================================

    private void clearFields() {

        txtPetName.setText("");

        txtBreed.setText("");

        txtDateOfBirth.setText("");

        txtWeight.setText("");

        txtNotes.setText("");

        txtSearch.setText("");


        if (cmbSpecies.getItemCount() > 0) {

            cmbSpecies.setSelectedIndex(0);
        }


        if (cmbGender.getItemCount() > 0) {

            cmbGender.setSelectedIndex(0);
        }


        if (cmbOwner.getItemCount() > 0) {

            cmbOwner.setSelectedIndex(0);
        }


        tblPets.clearSelection();

        txtPetName.requestFocus();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager
                            .getInstalledLookAndFeels()
                    ) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex
                ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(
                () -> new PetForm().setVisible(true)
        );
    
    }//GEN-LAST:event_btnSearchActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbOwner;
    private javax.swing.JComboBox<String> cmbSpecies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPets;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPetName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
