/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java
 * to edit this template
 */
package com.petcaremax.view;

import com.petcaremax.controller.ReportsPanelController;

/**
 * Reports Panel
 */
public class ReportsPanel extends javax.swing.JFrame {

    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
        initComponents();
        new ReportsPanelController(this);

        setLocationRelativeTo(null);
        setTitle("PetCareMAX - Reports");
    }

    // Return the report button so the controller can handle its event.
    public javax.swing.JButton getReportsButton() {
        return ReportsPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ReportsPanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ReportsPanel.setText("Appointment Report");

        javax.swing.GroupLayout layout =
                new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING
            )
            .addGroup(
                layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(
                    ReportsPanel,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    155,
                    javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addContainerGap(
                    214,
                    Short.MAX_VALUE
                )
            )
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING
            )
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                .addContainerGap(
                    240,
                    Short.MAX_VALUE
                )
                .addComponent(
                    ReportsPanel
                )
                .addGap(
                    37,
                    37,
                    37
                )
            )
        );

        pack();
    }
    // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(
            new Runnable() {
                public void run() {
                    new ReportsPanel().setVisible(true);
                }
            }
        );
    }

    // Variables declaration
    private javax.swing.JButton ReportsPanel;
    // End of variables declaration
}
