/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcaremax.view;

import com.petcaremax.controller.VeterinarianController;
import com.petcaremax.model.Veterinarian;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Bimsara
 */
public class VeterinarianForm extends javax.swing.JFrame {
    private final VeterinarianController veterinarianController =
        new VeterinarianController();
    
    private int selectedVeterinarianId = 0;
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(VeterinarianForm.class.getName());

    /**
     * Creates new form VeterinarianForm
     */
    public VeterinarianForm() {
        initComponents();
          // Load veterinarian records from database
        loadVeterinarians();
    }
 /**
     * Load all veterinarians into the JTable.
     */
    private void loadVeterinarians() {

        try {

            List<Veterinarian> veterinarians =
                    veterinarianController.getAllVeterinarians();

            DefaultTableModel model =
                    (DefaultTableModel) tblVeterinarians.getModel();

            // Remove existing rows
            model.setRowCount(0);

            // Add database records
            for (Veterinarian veterinarian : veterinarians) {

                model.addRow(new Object[]{
                    veterinarian.getVeterinarianId(),
                    veterinarian.getFullName(),
                    veterinarian.getSpecialization(),
                    veterinarian.getPhone(),
                    veterinarian.getEmail(),
                    veterinarian.getAvailability(),
                    veterinarian.getStatus()
                });
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load veterinarian records.\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeterinarians = new javax.swing.JTable();
        txtFullName = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(" VETERINARIAN MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 6, 180, 30));

        jLabel2.setText("Full Name   ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Specialization");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText(" Phone ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Availability");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 20));

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel8.setText("Search Veterinarian");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 150, 30));

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 20));

        tblVeterinarians.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Specialization", "Phone", "Email", "Availability", "Status"
            }
        ));
        tblVeterinarians.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeterinariansMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeterinarians);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 560, 140));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, -1));
        jPanel1.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 200, -1));
        jPanel1.add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void clearFields() {

    txtFullName.setText("");
    txtSpecialization.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    txtAvailability.setText("");

    cmbStatus.setSelectedItem("Active");

    txtFullName.requestFocus();
}
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String fullName = txtFullName.getText().trim();
String specialization = txtSpecialization.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String availability = txtAvailability.getText().trim();
String status = cmbStatus.getSelectedItem().toString();

if (fullName.isEmpty()) {
    JOptionPane.showMessageDialog(
            this,
            "Please enter veterinarian name.",
            "Validation",
            JOptionPane.WARNING_MESSAGE
    );
    txtFullName.requestFocus();
    return;
}

if (phone.isEmpty()) {
    JOptionPane.showMessageDialog(
            this,
            "Please enter phone number.",
            "Validation",
            JOptionPane.WARNING_MESSAGE
    );
    txtPhone.requestFocus();
    return;
}

try {

    Veterinarian veterinarian = new Veterinarian(
            0,
            fullName,
            specialization,
            phone,
            email,
            availability,
            status
    );

    boolean saved =
            veterinarianController.addVeterinarian(veterinarian);

    if (saved) {

        JOptionPane.showMessageDialog(
                this,
                "Veterinarian saved successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

        clearFields();
        loadVeterinarians();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Unable to save veterinarian.",
                "Save Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

} catch (IllegalArgumentException e) {

    JOptionPane.showMessageDialog(
            this,
            e.getMessage(),
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
    );

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "An unexpected error occurred:\n" + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
    );
    }//GEN-LAST:event_btnSaveActionPerformed
    }
    private void tblVeterinariansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeterinariansMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblVeterinarians.getSelectedRow();

 if (selectedRow >= 0) {

        selectedVeterinarianId = Integer.parseInt(
                tblVeterinarians
                        .getValueAt(selectedRow, 0)
                        .toString()
        );

        txtFullName.setText(
                tblVeterinarians
                        .getValueAt(selectedRow, 1)
                        .toString()
        );

        txtSpecialization.setText(
                tblVeterinarians
                        .getValueAt(selectedRow, 2)
                        .toString()
        );

        txtPhone.setText(
                tblVeterinarians
                        .getValueAt(selectedRow, 3)
                        .toString()
        );

        txtEmail.setText(
                tblVeterinarians
                        .getValueAt(selectedRow, 4)
                        .toString()
        );

        txtAvailability.setText(
                tblVeterinarians
                        .getValueAt(selectedRow, 5)
                        .toString()
        );

        cmbStatus.setSelectedItem(
                tblVeterinarians
                        .getValueAt(selectedRow, 6)
                        .toString()
        );
    }
    
    }//GEN-LAST:event_tblVeterinariansMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         if (selectedVeterinarianId == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a veterinarian from the table first."
        );
        return;
    }

    String fullName = txtFullName.getText().trim();
    String specialization = txtSpecialization.getText().trim();
    String phone = txtPhone.getText().trim();
    String email = txtEmail.getText().trim();
    String availability = txtAvailability.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();

    if (fullName.isEmpty() || phone.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Full Name and Phone are required."
        );
        return;
    }

    Veterinarian veterinarian = new Veterinarian(
            selectedVeterinarianId,
            fullName,
            specialization,
            phone,
            email,
            availability,
            status
    );

    try {
        boolean updated = veterinarianController.updateVeterinarian(veterinarian);

        if (updated) {
            JOptionPane.showMessageDialog(
                    this,
                    "Veterinarian updated successfully!"
            );

            clearFields();
            loadVeterinarians();

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update veterinarian."
            );
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          if (selectedVeterinarianId == 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a veterinarian from the table first."
        );
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this veterinarian?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        boolean deleted =
                veterinarianController.deleteVeterinarian(
                        selectedVeterinarianId
                );

        if (deleted) {

            JOptionPane.showMessageDialog(
                    this,
                    "Veterinarian deleted successfully!"
            );

            clearFields();
            loadVeterinarians();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to delete veterinarian."
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtFullName.setText("");
    txtSpecialization.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    txtAvailability.setText("");

    cmbStatus.setSelectedIndex(0);

    selectedVeterinarianId = 0;

    tblVeterinarians.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String searchText = txtSearch.getText().trim().toLowerCase();

    if (searchText.isEmpty()) {
        loadVeterinarians();
        return;
    }

    List<Veterinarian> veterinarians =
            veterinarianController.getAllVeterinarians();

    List<Veterinarian> filteredList = veterinarians.stream()
            .filter(v ->
                    String.valueOf(v.getVeterinarianId())
                            .contains(searchText)
                    || v.getFullName().toLowerCase()
                            .contains(searchText)
                    || (v.getSpecialization() != null
                            && v.getSpecialization().toLowerCase()
                                    .contains(searchText))
                    || v.getPhone().toLowerCase()
                            .contains(searchText)
                    || (v.getEmail() != null
                            && v.getEmail().toLowerCase()
                                    .contains(searchText))
                    || (v.getStatus() != null
                            && v.getStatus().toLowerCase()
                                    .contains(searchText))
            )
            .toList();

    DefaultTableModel model =
            (DefaultTableModel) tblVeterinarians.getModel();

    model.setRowCount(0);

    for (Veterinarian v : filteredList) {

        model.addRow(new Object[]{
            v.getVeterinarianId(),
            v.getFullName(),
            v.getSpecialization(),
            v.getPhone(),
            v.getEmail(),
            v.getAvailability(),
            v.getStatus()
        });
    }

    if (filteredList.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "No veterinarian found."
        );
    }
    }//GEN-LAST:event_btnSearchActionPerformed
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {

            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager
                            .getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VeterinarianForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVeterinarians;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
